import { mkdir, readFile, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { createApp } from '../server.mjs';
import { Vision } from '../lib/vision.mjs';
import { browserTools } from './browser.mjs';
// Self-hosted on a free port with a synthetic signed-in status, so it never needs the desktop app quit or a real login.
// Model responses come from the recorded verify:vision fixtures via page.route, never from inference.
const vision = new Vision({ status:async () => ({ configured:true,cli:true }),inference:async () => { throw new Error('verify-browser must not call inference'); } });
const app = createApp({ vision }); await new Promise(resolve => app.listen(0,'127.0.0.1',resolve));
const origin = `http://127.0.0.1:${app.address().port}`;
const { chromium } = browserTools();
await mkdir('.artifacts',{ recursive:true });
const browser = await chromium.launch({ channel:'chrome',headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream'] });
const context = await browser.newContext({ viewport:{ width:1440,height:1100 },permissions:['camera'] });
const page = await context.newPage(); const errors = [];
page.on('pageerror',error => errors.push(error.message));
const checks = [];
try {
  await page.goto(origin);
  await page.locator('#provider-status').filter({ hasText:/^Astra · (low|medium|high|xhigh|max)$/ }).waitFor();
  assert.ok(await page.locator('#companion').isVisible(),'the column stays beside the studio at 1440');
  await page.screenshot({ path:'.artifacts/workbench-desktop.png',fullPage:true });
  checks.push('desktop initial render with the column beside the studio');
  await page.getByRole('button',{ name:'Connect camera',exact:true }).click();
  await page.getByText('Camera on · local only',{ exact:true }).waitFor();
  assert.ok(await page.locator('#camera').evaluate(video => video.videoWidth > 0));
  await page.getByRole('button',{ name:'Turn off',exact:true }).click();
  assert.equal(await page.locator('#camera').evaluate(video => video.srcObject),null);
  checks.push('camera permission, frame, and stream stop (synthetic device)');
  await page.getByRole('button',{ name:'Try a sample sketch' }).click();
  await page.locator('#reference').evaluate(img => img.decode());
  assert.match(await page.locator('#frame-label').innerText(),/Sample sketch/);
  let cloudRequests = 0; const bodies = [];
  page.on('request',r => { if (/\/api\/(build|observe)$/.test(r.url())) { cloudRequests++; bodies.push(r.postDataJSON()); } });
  await page.locator('#frame-chip').waitFor();assert.equal(await page.locator('#build-label').innerText(),'Build with frame');
  assert.equal(await page.locator('#composer input[type=checkbox]').count(),0,'no tick in the composer');
  const sketchDirection=await page.locator('#direction').inputValue();await page.locator('#direction').fill('');
  await page.locator('#build').click();
  assert.match(await page.locator('#error-text').innerText(),/Tell Sidelook what should work first/);
  assert.equal(cloudRequests,0);await page.locator('#direction').fill(sketchDirection);
  checks.push('sample labeled and attached; the button says the frame goes; an empty direction makes zero cloud requests');

  // Use the actual result of verify:vision to test the rendered output, without another paid call.
  const generated = JSON.parse(await readFile('.artifacts/generated.json','utf8'));
  const observed = JSON.parse(await readFile('.artifacts/observation.json','utf8'));
  assert.equal(generated.model,'gpt-6-astra');
  assert.equal(observed.model,'gpt-6-astra');
  await page.route('**/api/observe',route => route.fulfill({ json:observed }));
  await page.route('**/api/build',route => route.fulfill({ json:generated }));
  await page.locator('#build').click();
  await page.locator('#version-label').filter({ hasText:'VERSION 01' }).waitFor();
  assert.equal(cloudRequests,1); assert.equal(typeof bodies[0].image,'string');
  assert.equal(await page.locator('#frame-chip').isHidden(),true,'the frame leaves the box after it went');
  assert.equal(await page.locator('#build-label').innerText(),'Revise Version 01','the button names the version the next direction revises');
  const frame = page.frameLocator('#preview');
  await frame.locator('body').waitFor();
  assert.match(await frame.locator('body').innerText(),/DAYLIGHT/i);
  checks.push('generated app renders inside sandbox (recorded real provider response); tick and include clear');
  await page.locator('#direction').fill('Make the heading smaller');
  await page.locator('#build').click();
  await page.locator('#version-label').filter({ hasText:'VERSION 02' }).waitFor();
  assert.equal(cloudRequests,2); assert.equal(bodies[1].image,null);
  checks.push('the frame rides only while it is attached in the box');
  await page.getByRole('button',{ name:'Mobile preview',exact:true }).click();
  assert.equal(Math.round((await page.locator('#preview').boundingBox()).width),375);
  await page.getByRole('button',{ name:'Desktop preview',exact:true }).click();
  await page.getByRole('button',{ name:'Source',exact:true }).click();
  assert.match(await page.locator('#source-code').textContent(),/<!doctype html>/i);
  await page.getByRole('button',{ name:'Close source' }).click();
  const downloading = page.waitForEvent('download');
  await page.getByRole('button',{ name:'Download',exact:true }).click();
  assert.match((await downloading).suggestedFilename(),/\.html$/);
  checks.push('mobile preview, source inspection, and HTML download');
  await page.screenshot({ path:'.artifacts/workbench-built.png',fullPage:true });
  await page.reload();
  await page.locator('#version-label').filter({ hasText:'VERSION 02' }).waitFor();
  assert.match(await frame.locator('body').innerText(),/DAYLIGHT/i);
  checks.push('version and evidence restored from browser storage');
  await page.setViewportSize({ width:1100,height:900 });
  assert.equal(await page.locator('#companion').isVisible(),false,'the column steps aside below 1180');
  await page.setViewportSize({ width:390,height:844 });
  await page.screenshot({ path:'.artifacts/workbench-mobile.png',fullPage:true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  checks.push('390px mobile layout without horizontal overflow');
  await page.getByRole('button',{ name:'New project',exact:true }).click();
  await page.getByRole('button',{ name:'Clear and start fresh',exact:true }).click();
  await page.getByText('Your first version starts with an idea.',{ exact:true }).waitFor();
  await page.reload();
  await page.locator('#provider-status').filter({ hasText:/^Astra · (low|medium|high|xhigh|max)$/ }).waitFor();
  assert.equal(await page.locator('.revision').count(),0);
  checks.push('new-project purge survives reload');
  assert.deepEqual(errors,[]);
  await writeFile('.artifacts/browser-report.json',JSON.stringify({ checks,errors },null,2));
  console.log(`PASS: ${checks.length} browser checks, ${errors.length} page errors.\n${checks.map(c=>`- ${c}`).join('\n')}`);
} finally { await browser.close(); await new Promise(resolve => app.close(resolve)); }
