import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createApp} from '../server.mjs';
import {Vision} from '../lib/vision.mjs';
import {browserTools} from './browser.mjs';
const html=await readFile('public/demo.html','utf8');let publish,release;
const vision=new Vision({status:async()=>({configured:true,cli:true}),inference:async(data,signal,progress)=>{
  publish=progress;progress({type:'phase',phase:'waiting',streaming:true});
  await new Promise(r=>release=r);
  return {model:'claude-fable-5-1',effort:data.effort,result:{title:'Stream complete',reply:'Synthetic result',changes:[],html}};
}});
const app=createApp({vision});await new Promise(r=>app.listen(0,'127.0.0.1',r));
const {chromium}=browserTools();const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const idle=()=>page.waitForFunction(()=>!document.querySelector('#build').disabled);
try {
  await page.goto(`http://127.0.0.1:${app.address().port}`);await idle();await page.locator('#try-demo').click();
  await page.frameLocator('#preview').locator('#todo').waitFor();
  await page.locator('#model-choice').selectOption('fable');await idle();
  await page.locator('#faster-effort').click();await idle();assert.equal(await page.locator('#effort-choice').inputValue(),'low');
  await page.locator('#direction').fill('Build gradually');await page.locator('#build').click();await page.locator('#accept-consent').click();
  await page.waitForFunction(()=>document.querySelector('#build-phase').textContent==='WAITING FOR MODEL OUTPUT');
  const first='<html><head><style>body{background:#ede5d3;font:24px Georgia;padding:32px}</style></head><body><h1>First real chunk</h1><script>document.body.dataset.executed="yes"</script>';
  publish({type:'draft',html:first});
  await page.frameLocator('#draft-preview').getByRole('heading',{name:'First real chunk'}).waitFor();
  assert.equal(await page.locator('.revision').count(),1);
  assert.equal(await page.frameLocator('#draft-preview').locator('body').getAttribute('data-executed'),null);
  assert.equal(await page.locator('#draft-preview').getAttribute('sandbox'),'');
  publish({type:'draft',html:first+'<h2>A second section arrives</h2>'});
  await page.frameLocator('#draft-preview').getByRole('heading',{name:'A second section arrives'}).waitFor();
  assert.match(await page.locator('#draft-code').textContent(),/A second section/);
  await page.locator('#show-working').click();
  await page.frameLocator('#preview').getByRole('textbox',{name:'Task title',exact:true}).fill('Keep working');
  await page.frameLocator('#preview').getByRole('button',{name:'Add task',exact:true}).click();
  assert.match(await page.frameLocator('#preview').locator('#todo').innerText(),/Keep working/);
  await page.locator('#show-draft').click();await page.screenshot({path:'.artifacts/stream-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.screenshot({path:'.artifacts/stream-mobile.png',fullPage:true});
  await page.locator('#cancel').click();release();await idle();
  assert.equal(await page.locator('.revision').count(),1);assert.equal(await page.locator('#draft-controls').isHidden(),true);
  assert.match(await page.frameLocator('#preview').locator('#todo').innerText(),/Keep working/);
  await page.locator('#direction').fill('Finish this draft');await page.locator('#build').click();
  await page.waitForFunction(()=>document.querySelector('#build-phase').textContent==='WAITING FOR MODEL OUTPUT');
  publish({type:'draft',html:first});await page.locator('#draft-controls').waitFor({state:'visible'});release();await idle();
  assert.equal(await page.locator('.revision').count(),2);assert.equal(await page.locator('#draft-controls').isHidden(),true);
  await page.frameLocator('#preview').getByRole('textbox',{name:'Task title',exact:true}).fill('Final scripts work');
  await page.frameLocator('#preview').getByRole('button',{name:'Add task',exact:true}).click();
  assert.match(await page.frameLocator('#preview').locator('#todo').innerText(),/Final scripts work/);
  assert.equal(errors.length,0);
  console.log('PASS: 14 streaming browser checks: low-effort shortcut, early draft, incremental section, source text, scripts blocked, sandbox, working-version toggle and interaction, mobile fit, cancellation discards draft, working state preserved, validated completion, final interactions, zero page errors.');
} finally {release?.();await browser.close();await new Promise(r=>app.close(r));}
